/*
 * Durable AI agent harness persistence for MySQL 8.
 *
 * This migration is intentionally create-only. Flyway must surface an existing
 * conflicting table instead of silently accepting schema drift.
 */

SET NAMES utf8mb4;

CREATE TABLE `ai_agent_run` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `request_idempotency_key` varchar(128) NOT NULL COMMENT 'Caller request idempotency key',
    `agent_id` bigint NOT NULL COMMENT 'Agent definition ID',
    `agent_version` int NOT NULL COMMENT 'Agent definition version snapshot',
    `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Durable run status',
    `risk_level` varchar(32) NOT NULL DEFAULT 'LOW' COMMENT 'Highest observed risk level',
    `input_payload` json NOT NULL COMMENT 'Run input payload',
    `output_payload` json DEFAULT NULL COMMENT 'Run output payload',
    `context_snapshot` json DEFAULT NULL COMMENT 'Invocation context snapshot',
    `model_snapshot` json DEFAULT NULL COMMENT 'Model configuration snapshot',
    `policy_snapshot` json DEFAULT NULL COMMENT 'Policy configuration snapshot',
    `execution_snapshot` json DEFAULT NULL COMMENT 'Resumable execution state',
    `attempt_count` int NOT NULL DEFAULT 0 COMMENT 'Completed execution attempts',
    `max_attempts` int NOT NULL DEFAULT 3 COMMENT 'Maximum execution attempts',
    `next_retry_at` datetime(3) DEFAULT NULL COMMENT 'Next eligible retry time',
    `lease_owner` varchar(128) DEFAULT NULL COMMENT 'Current lease owner',
    `lease_expires_at` datetime(3) DEFAULT NULL COMMENT 'Current lease expiry time',
    `version` int NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    `error_code` varchar(64) DEFAULT NULL COMMENT 'Stable failure code',
    `error_message` varchar(2000) DEFAULT NULL COMMENT 'Failure message',
    `error_details` json DEFAULT NULL COMMENT 'Structured failure details',
    `started_at` datetime(3) DEFAULT NULL COMMENT 'Execution start time',
    `completed_at` datetime(3) DEFAULT NULL COMMENT 'Execution completion time',
    `user_id` bigint NOT NULL COMMENT 'Owning user ID',
    `tenant_id` bigint NOT NULL COMMENT 'Owning tenant ID',
    `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Logical deletion flag',
    `create_by` bigint DEFAULT NULL COMMENT 'Creator ID',
    `create_name` varchar(255) DEFAULT NULL COMMENT 'Creator name',
    `create_time` datetime DEFAULT NULL COMMENT 'Creation time',
    `last_modify_by` bigint DEFAULT NULL COMMENT 'Last modifier ID',
    `last_modify_name` varchar(255) DEFAULT NULL COMMENT 'Last modifier name',
    `last_modify_time` datetime DEFAULT NULL COMMENT 'Last modification time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agent_run_tenant_request` (`tenant_id`, `request_idempotency_key`),
    KEY `idx_agent_run_runnable` (`status`, `next_retry_at`, `lease_expires_at`),
    KEY `idx_agent_run_tenant_user_status` (`tenant_id`, `user_id`, `status`, `create_time`),
    KEY `idx_agent_run_agent_version` (`agent_id`, `agent_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Durable AI agent runs';

CREATE TABLE `ai_agent_run_step` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `run_id` bigint NOT NULL COMMENT 'Owning run ID',
    `step_id` varchar(128) NOT NULL COMMENT 'Stable step identifier within the run',
    `step_type` varchar(64) NOT NULL COMMENT 'Step implementation type',
    `step_name` varchar(255) DEFAULT NULL COMMENT 'Display name snapshot',
    `idempotency_key` varchar(128) NOT NULL COMMENT 'Side effect idempotency key',
    `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Durable step status',
    `risk_level` varchar(32) NOT NULL DEFAULT 'LOW' COMMENT 'Step risk level',
    `input_payload` json DEFAULT NULL COMMENT 'Step input payload',
    `output_payload` json DEFAULT NULL COMMENT 'Step output payload',
    `execution_snapshot` json DEFAULT NULL COMMENT 'Resumable step state',
    `attempt_count` int NOT NULL DEFAULT 0 COMMENT 'Completed step attempts',
    `max_attempts` int NOT NULL DEFAULT 3 COMMENT 'Maximum step attempts',
    `next_retry_at` datetime(3) DEFAULT NULL COMMENT 'Next eligible retry time',
    `lease_owner` varchar(128) DEFAULT NULL COMMENT 'Current lease owner',
    `lease_expires_at` datetime(3) DEFAULT NULL COMMENT 'Current lease expiry time',
    `version` int NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    `error_code` varchar(64) DEFAULT NULL COMMENT 'Stable failure code',
    `error_message` varchar(2000) DEFAULT NULL COMMENT 'Failure message',
    `error_details` json DEFAULT NULL COMMENT 'Structured failure details',
    `started_at` datetime(3) DEFAULT NULL COMMENT 'Step start time',
    `completed_at` datetime(3) DEFAULT NULL COMMENT 'Step completion time',
    `user_id` bigint NOT NULL COMMENT 'Owning user ID',
    `tenant_id` bigint NOT NULL COMMENT 'Owning tenant ID',
    `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Logical deletion flag',
    `create_by` bigint DEFAULT NULL COMMENT 'Creator ID',
    `create_name` varchar(255) DEFAULT NULL COMMENT 'Creator name',
    `create_time` datetime DEFAULT NULL COMMENT 'Creation time',
    `last_modify_by` bigint DEFAULT NULL COMMENT 'Last modifier ID',
    `last_modify_name` varchar(255) DEFAULT NULL COMMENT 'Last modifier name',
    `last_modify_time` datetime DEFAULT NULL COMMENT 'Last modification time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agent_step_run_step` (`run_id`, `step_id`),
    UNIQUE KEY `uk_agent_step_tenant_idempotency` (`tenant_id`, `idempotency_key`),
    KEY `idx_agent_step_runnable` (`status`, `next_retry_at`, `lease_expires_at`),
    KEY `idx_agent_step_tenant_user_status` (`tenant_id`, `user_id`, `status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Durable AI agent run steps';

CREATE TABLE `ai_agent_approval` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `run_id` bigint NOT NULL COMMENT 'Owning run ID',
    `step_id` varchar(128) NOT NULL COMMENT 'Step awaiting approval',
    `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Approval status',
    `risk_level` varchar(32) NOT NULL COMMENT 'Risk level presented for approval',
    `request_payload` json DEFAULT NULL COMMENT 'Approval request snapshot',
    `decision_payload` json DEFAULT NULL COMMENT 'Structured decision data',
    `decision_reason` varchar(1000) DEFAULT NULL COMMENT 'Human decision reason',
    `decided_by` bigint DEFAULT NULL COMMENT 'Decision maker user ID',
    `requested_at` datetime(3) NOT NULL COMMENT 'Approval request time',
    `decided_at` datetime(3) DEFAULT NULL COMMENT 'Decision time',
    `expires_at` datetime(3) DEFAULT NULL COMMENT 'Approval expiry time',
    `version` int NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    `user_id` bigint NOT NULL COMMENT 'Owning user ID',
    `tenant_id` bigint NOT NULL COMMENT 'Owning tenant ID',
    `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Logical deletion flag',
    `create_by` bigint DEFAULT NULL COMMENT 'Creator ID',
    `create_name` varchar(255) DEFAULT NULL COMMENT 'Creator name',
    `create_time` datetime DEFAULT NULL COMMENT 'Creation time',
    `last_modify_by` bigint DEFAULT NULL COMMENT 'Last modifier ID',
    `last_modify_name` varchar(255) DEFAULT NULL COMMENT 'Last modifier name',
    `last_modify_time` datetime DEFAULT NULL COMMENT 'Last modification time',
    PRIMARY KEY (`id`),
    KEY `idx_agent_approval_run_step` (`run_id`, `step_id`, `status`),
    KEY `idx_agent_approval_decision` (`tenant_id`, `user_id`, `status`, `expires_at`),
    KEY `idx_agent_approval_decided_by` (`tenant_id`, `decided_by`, `decided_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI agent human approvals';

CREATE TABLE `ai_agent_event` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `run_id` bigint NOT NULL COMMENT 'Owning run ID',
    `step_id` varchar(128) DEFAULT NULL COMMENT 'Related step identifier',
    `sequence_no` bigint NOT NULL COMMENT 'Monotonic event sequence within the run',
    `event_type` varchar(64) NOT NULL COMMENT 'Event type',
    `status` varchar(32) NOT NULL COMMENT 'Status captured by the event',
    `payload` json DEFAULT NULL COMMENT 'Event payload',
    `occurred_at` datetime(3) NOT NULL COMMENT 'Event occurrence time',
    `user_id` bigint NOT NULL COMMENT 'Owning user ID',
    `tenant_id` bigint NOT NULL COMMENT 'Owning tenant ID',
    `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Logical deletion flag',
    `create_by` bigint DEFAULT NULL COMMENT 'Creator ID',
    `create_name` varchar(255) DEFAULT NULL COMMENT 'Creator name',
    `create_time` datetime DEFAULT NULL COMMENT 'Creation time',
    `last_modify_by` bigint DEFAULT NULL COMMENT 'Last modifier ID',
    `last_modify_name` varchar(255) DEFAULT NULL COMMENT 'Last modifier name',
    `last_modify_time` datetime DEFAULT NULL COMMENT 'Last modification time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agent_event_run_sequence` (`run_id`, `sequence_no`),
    KEY `idx_agent_event_tenant_user` (`tenant_id`, `user_id`, `create_time`),
    KEY `idx_agent_event_tenant_status` (`tenant_id`, `user_id`, `status`, `create_time`),
    KEY `idx_agent_event_type` (`run_id`, `event_type`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Ordered AI agent run events';

CREATE TABLE `ai_agent_feedback` (
    `id` bigint NOT NULL COMMENT 'Primary key',
    `run_id` bigint NOT NULL COMMENT 'Related run ID',
    `step_id` varchar(128) DEFAULT NULL COMMENT 'Related step identifier',
    `feedback_type` varchar(32) NOT NULL COMMENT 'Feedback classification',
    `rating` int DEFAULT NULL COMMENT 'Optional numeric rating',
    `comment` varchar(2000) DEFAULT NULL COMMENT 'User feedback text',
    `payload` json DEFAULT NULL COMMENT 'Structured feedback details',
    `user_id` bigint NOT NULL COMMENT 'Submitting user ID',
    `tenant_id` bigint NOT NULL COMMENT 'Owning tenant ID',
    `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Logical deletion flag',
    `create_by` bigint DEFAULT NULL COMMENT 'Creator ID',
    `create_name` varchar(255) DEFAULT NULL COMMENT 'Creator name',
    `create_time` datetime DEFAULT NULL COMMENT 'Creation time',
    `last_modify_by` bigint DEFAULT NULL COMMENT 'Last modifier ID',
    `last_modify_name` varchar(255) DEFAULT NULL COMMENT 'Last modifier name',
    `last_modify_time` datetime DEFAULT NULL COMMENT 'Last modification time',
    PRIMARY KEY (`id`),
    KEY `idx_agent_feedback_run` (`run_id`, `create_time`),
    KEY `idx_agent_feedback_tenant_user` (`tenant_id`, `user_id`, `create_time`),
    KEY `idx_agent_feedback_type` (`tenant_id`, `feedback_type`, `rating`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='User feedback for AI agent runs';
